# Generated by Django 3.0.7 on 2020-06-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='images')),
                ('date', models.DateTimeField(verbose_name='auto_now_add')),
            ],
            options={
                'verbose_name': 'Bushido Articles',
                'db_table': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='NewRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Others', 'Others')], default='gender', max_length=6)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to='Registered_folks')),
            ],
        ),
    ]
