# Generated by Django 3.0.7 on 2020-06-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newregistration',
            options={'verbose_name': 'New Registration'},
        ),
        migrations.AlterModelTable(
            name='newregistration',
            table='NewRegistration',
        ),
    ]
