# Generated by Django 3.0.7 on 2020-06-27 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200627_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='newregistration',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='auto_now_add'),
            preserve_default=False,
        ),
    ]
