# Generated by Django 3.0.7 on 2020-06-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200627_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newregistration',
            options={},
        ),
        migrations.AlterModelTable(
            name='newregistration',
            table=None,
        ),
    ]
